baseURL = 'https://annamarburger.github.io/SketchingWithHardware/'
languageCode = 'en-us'
title = 'Anna Marburger'
theme = "ananke"

[params]
  text_color = ""
  author = "Anna Marburger"
  favicon = "media/qboyicon.png"
  site_logo = "media/logo.png"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-near-black"
  recent_posts_number = 10


